//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class WLANConnectionDef : IConnectionDef
{

	public string Ip {
		get; private set;
	}

	public int Port {
		get; private set;
	}

	public WLANConnectionDef (string ip, int port)
	{
		this.Ip = ip;
		this.Port = port;
	}

}

